### ISSUE TITLE
mnsl2hex argument fix = TRUE is not passed on

### ISSUE THREAD

**Issue by bryanhanson** [cwickham/munsell#10]
MWE:

```
mnsl2hex("5PB 5/10") # OK
mnsl2hex("5PB 5/10", fix = TRUE) # Error unused argument
```

I was going to try to fork and fix, but there may be a design decision in play that I don't understand., or possibly stale code was pushed to Github accidently.  Looking at the code for `mnsl2hex` the documentation is clear that `fix = TRUE` will be passed to `check_mnsl`.  However, looking at the code for `check_mnsl` it cannot accept any arguments but `col`.  It also never calls any functions which appear as though they could fix any problems.  If `fix` were in the arguments, it should probably result to a call to `in_gamut` which in turn will call `fix_mnsl`.  I know `fix = TRUE` worked about 3 years ago -- I discovered this problem while trying to resurrect some old code.

**Comment by cwickham** [comment]
Yeah, this seems like a bug, or at least a conflict between docs and code.  I found this note to myself:
> Also don't fix, check, because that limits ability to chain, i.e. darker(saturate)

But, I don't this this is relevant here...  It seems reasonable to me, that `mnsl2hex()` should have the `fix` argument, and it should be passed on to `check_mnsl()`, and therefore `check_mnsl()` should have a `fix` argument (with a `FALSE` default) and pass it on to `in_gamut()`.  

If you want to submit a fix I'd be really grateful!  If you do, could you also:
* add a test too, it doesn't need to be much more complicated that your example above
* add an item to NEWS

Let me know if you run into any trouble or want more input.

**Comment by cwickham** [comment]
FYI this seems to be the commit in which I removed `fix` from `check_mnsl()`
https://github.com/cwickham/munsell/commit/ce6b7fedfd75b3450b9060ac536402413e6c1bd6

**Comment by bryanhanson** [comment]
Will do, w/i a few days. Bryan
